### ISSUE TITLE
Problem with python 3

### ISSUE THREAD

**Issue by JulianSchl** [precice/mbdyn-adapter#5]
Hi,

I am currently trying to run the MBDyn adapter.
To interact with precice, the adapter uses pyprecice to communicate.
However it appeared, that pyprecice is only available for Python 3, while the adapter is running using Python 2.
Is there any solution to fix this issue?

**Comment by BenjaminRodenberg** [comment]
Hi Julian,

Python 2 is officially "dead" (see https://pythonclock.org/). According to https://public.gitlab.polimi.it/DAER/mbdyn/-/issues/37 MBDyn should work with Python 3. Note that the pyprecice also only supports Python 3.

I'm not sure about the state of the adapter, but if it only supports Python 2, this should be changed and Python 3 should be supported (If necessary sacrificing Python 2 support). Quickly skimming the source code of the adapter I do not see any obvious Python 2 vs. Python 3 issues, but I might be missing something.

I would suggest to use the Python 3 interface of MBDyn and pyprecice. Then try to run the adapter with Python 3. If compatibility pop up in the adapter, this is something that should be solved in favor of Python 3 compatibility. If you have a working version of the adapter (with Python 3) that would also be a very useful contribution.

**Comment by JulianSchl** [comment]
Hi Benjamin,
thank you for your answer!
Running the tutorial code of the adapter (`tutorials/cavityFSI/structure$ python3 cavityFSI.py`), I am getting the following output:
`Import Error: mbc_py module
Traceback (most recent call last):
  File "cavityFSI.py", line 3, in <module>
    mbd.readMsh('membrane.msh')
  File "/home/julian/software/mbdyn-adapter/mbdynAdapter/helper.py", line 73, in readMsh
    if cells[1] == 1:
TypeError: 'map' object is not subscriptable`

This error occurs because of the `map` operator in `helper.py` of the mbdyn-adapter, which seems to have the syntax of python2.

**Comment by Ccaccia73** [comment]
Hi @JulianSchl ,
as @BenjaminRodenberg  observed, this adapter works with python2 and it isn't currently maintained. We developed a new one at Politecnico of Milan. We plan to present some interesting results at the next Coupled Problems conference, but at the moment it is not an official adapter. If you are interested in developing something with MBDyn and preCICE we can get in touch and see if I can help you.

**Comment by JulianSchl** [comment]
Hi @Ccaccia73,

thank you for your help proposal.
Currently, I am trying to run a simplified version of the example script of the MBDyn-Adapter in python.
For the beginning I am trying to simulate an easy case: A single node with force impact in MBDyn.

Therefore I took the [example from github](https://github.com/precice/mbdyn-adapter/tree/master/tutorials/cavityFSI) and tried to modify it to match the simplified case with one node.
However running the iterations in preCICE, it seems that the socket communication is not working properly in my case.
The file [adapter.py](https://github.com/precice/mbdyn-adapter/blob/master/mbdynAdapter/adapter.py) is including [helper.py](https://github.com/precice/mbdyn-adapter/blob/master/mbdynAdapter/helper.py), which has the function `def solve(self, converged = True):` I am struggling with.

I am not really sure, if the socket is receiving data, but I get the following feedback after executing the command `self.nodal.send(False)`:
```
cmd to peer: 6 (REGULAR_DATA_AND_GOTO_NEXT_STEP)
Sending node dynamics data
Sent 24 bytes, dynamics size is 24
0
```
I assume the sending of data to the MBDyn socket was successful.

Now looking on the receiving function, I am getting the following feedback after executing `self.nodal.recv()`:
```
cmd from peer: 5 (ABORT)
got ABORT from peer
-1
```


Please also see the full code in the attached files ([mbdyn-adapter.zip](https://github.com/precice/mbdyn-adapter/files/6461292/mbdyn-adapter.zip)).
To run the code, you have to export the MBDyn and MBDyn-Adapter libraries to pythonpath and execute the following commands in two different terminals inside the `/mbdyn-adapter_ishaan/tutorials/cavityFSI/structure` folder:
`python cavityFSI.py precice-config.xml SolverOne MeshOne`
`python cavityFSI.py precice-config.xml SolverTwo MeshTwo`
Maybe it is possible for you to shortly look over the code.
If you have another easier example than the [example from github](https://github.com/precice/mbdyn-adapter/tree/master/tutorials/cavityFSI) I would also be very glad, if you could share it with me.

Thank You!
